driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY'] %>
  security_group_ids:  <%= ENV['AWS_SECURITY_GROUPS'] %>
  region: <%= ENV['AWS_REGION'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
  require_chef_omnibus: true
  subnet_id: <%= ENV['AWS_SUBNET'] %>
  associate_public_ip: false
  interface: private
  tags:
    OWNER: <%= ENV['AWS_OWNER_TAG'] %>
    Name: <%= ENV['AWS_NAME_TAG'] %>

provisioner:
  name: chef_zero
  log_level: <%= ENV['CHEF_LOG_LEVEL'] || 'auto' %>

transport:
  ssh_key: ~/.ssh/<%= ENV['AWS_SSH_KEY'] %>.pem

platforms:
  - name: gci-centos-72
    driver:
      image_id: <%= ENV['AWS_GCI_CENTOS7_AMI_ID'] %>
      instance_type: <%= ENV['LINUX_INSTANCE_SIZE'] %>
      user_data: <%= ENV['LINUX_USER_DATA_PATH'] %>
    transport:
      username: <%= ENV['AWS_CENTOS7_USERNAME'] %>
  - name: windows-2012r2
    driver:
      box: mwrock/Windows2012R2
      communicator: winrm
      shell_type: powershell
    provisioner:
      require_chef_omnibus: true

suites:
  - name: install_only
    run_list:
      - recipe[gd-test-helper::default]
      - recipe[apt::default]
      - recipe[consul::default]
      - recipe[consul-template::install_binary]
    excludes: ['windows-2012r2']
    attributes:
      apt:
        compile_time_update: true
      consul:
        config:
          bootstrap_expect: 1
          server: true
  - name: default
    run_list:
      - recipe[gd-test-helper::default]
      - recipe[apt::default]
      - recipe[consul::default]
      - recipe[consul-template::default]
      - recipe[consul-template-spec::consul_template_config]
    excludes: ['gannett/gci-centos-72', 'windows-2012r2']
    attributes:
      apt:
        compile_time_update: true
      consul:
        config:
          bootstrap_expect: 1
          server: true
      consul_template:
        config:
          consul: '127.0.0.1:8500'
  - name: systemd
    run_list:
      - recipe[gd-test-helper::default]
      - recipe[consul::default]
      - recipe[consul-template::default]
      - recipe[consul-template-spec::consul_template_config]
    includes: ['gannett/gci-centos-72']
    attributes:
      consul:
        init_style: 'systemd'
        config:
          bootstrap_expect: 1
          server: true
      consul_template:
        init_style: 'systemd'
        config:
          consul: '127.0.0.1:8500'
  - name: windows
    run_list:
      - recipe[gd-test-helper::default]
      - recipe[consul::default]
      - recipe[consul-template::default]
      - recipe[consul-template-spec::consul_template_config_win]
    includes: ['windows-2012r2']
    attributes:
      consul:
        config:
          bootstrap_expect: 1
          server: true
      consul_template:
        config:
          consul: '127.0.0.1:8500'
