---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: gannett/gci-centos-72
    network:
        - ["forwarded_port", {guest: 80, host: 8500}]

suites:
  - name: systemd
    data_bags_path: test/integration/data_bags
    run_list:
      - recipe[gd-test-helper::default]
      - recipe[consul::default]
      - recipe[consul-template::default]
      - recipe[consul-template-spec::consul_template_config]
    includes: ['gannett/gci-centos-72']
    attributes:
      consul:
        init_style: 'systemd'
        config:
          bootstrap_expect: 1
          server: true
      consul_template:
        init_style: 'systemd'
        config:
          consul: '127.0.0.1:8500'
